language: java
script: mvn clean verify -f bundle/fr.univnantes.alma.releng/pom.xml
jdk: oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: ayv98c8RDL4JJhEsjqf2t3/wAtp3JX5IJecOenyZ6MGM0sr4VsrhYxRXVFA8hIHY2/uHCl8k5woSR/c5DExyOPExJt1uBlYKvXHafdCR7j/uWev7BSRfisypcQM2wzyQZzZp6wws0LZK4DOKwfCK7kKvY5a7wrQukr24bvXnaCQh8ZZocaarjsaUSueUmtZNDhnwSs4DvAm4hZEUZUFmprE7C3/vOscJkhMWNIt67osnP4mgvMbK6ya9OZ2JMHwj+SioeDTqmCvwnbGBFZyCOr7oRs+/WD60X9Mx0npBCjiwWvOji5/dlgj9lpjoXh+JGLm4yVMVZ+cquwVVnBjRli9rpWM7/PBplVGueaRAP3zu3WDP0am28r4T1aztN5ayN6zXr7wk3crdANCkJjjE9Ol5AMtsoNWVd0fPv/wqBp1idI/094JzoapI3TCZUpBmYxd+7hoKVoBlhj4fZ1ZlJm8o14D68rHZnEJhAcyqxC8cLLPFIOWM4zSCnBDr1S6vru2PnNkqEB0htuEYMHW8AFjV777r289GfQlXGxUiJ1WFWsL7HwTHfOvlB7FMVKK4C1OkSn0sRvNCpUUcd76efNs/nr+5WhXFtNAhl3Wfz8jb3RjygX6dhAqzNbVtOQcsRM9HLdPRC8+FkvaT6bbTEAgz0tXfMLa9GOFBGktUIII=
  file_glob: true
  file: bundle/fr.univnantes.alma.repository/target/products/ALMAServer-*.zip
  on:
    repo: masters-info-nantes/commit-or-not-commit
